# TODO: this eanglish error map is deprecated, delete.
ERROR_MAP: dict[str, str] = {
    "p": "Como en 'papa'. Es un sonido bilabial sordo.",
    "b": "Como en 'banco'. Es un sonido bilabial sonoro.",
    "t": "Como en 'taco'. Es un sonido alveolar sordo.",
    "d": "Como en 'deber'. Es un sonido alveolar sonoro.",
    "k": "Como en 'casa'. Es un sonido velar sordo.",
    "g": "Como en 'gato'. Es un sonido velar sonoro.",
    "m": "Como en 'mamá'. Es un sonido bilabial nasal.",
    "n": "Como en 'nube'. Es un sonido alveolar nasal.",
    "ŋ": "Como en 'sing' (no tiene equivalente en español). Es un sonido nasal velar.",
    "f": "Como en 'flor'. Es un sonido labiodental sordo.",
    "v": "Como en 'vaca'. Puede ser un sonido labiodental sonoro, similar al 'b' en algunas regiones.",
    "θ": "Como en 'cima' (en España). Es un sonido dental sordo, no lo hay en español latino.",
    "ð": "Como en 'this'. No tiene equivalente en español.",
    "s": "Como en 'sopa'. Es un sonido alveolar sordo.",
    "z": "Como en 'casa' (en algunas regiones de España). Es un sonido alveolar sonoro.",
    "ʃ": "Como en 'shampoo'. No tiene equivalente en español.",
    "ʒ": "Como en 'measure'. No tiene equivalente en español.",
    "h": "Como en 'hola' (en inglés suele ser un sonido glotal sordo).",
    "l": "Como en 'luz'. Es un sonido alveolar lateral.",
    "r": "Como en 'ratón'. Es un sonido alveolar que puede ser vibrante.",
    "j": "Como en 'yo'. Es un sonido palatal aproximante.",
    "w": "Como en 'huevo'. Es un sonido labio-velar aproximante.",
    "i": "Como en 'sí'. Es una vocal cerrada anterior no redondeada.",
    "ɪ": "Como en 'bit'. No tiene equivalente exacto en español.",
    "e": "Como en 'rey'. Es una vocal media anterior no redondeada, similar a la diptongación en español.",
    "æ": "Como en 'cat'. No tiene equivalente directo en español.",
    "ʌ": "Como en 'cup'. No hay un equivalente exacto en español.",
    "ɔ": "Como en 'thought'. No tiene equivalente directo en español.",
    "o": "Como en 'fotografía'. Es una vocal cerrada posterior redondeada.",
    "ʊ": "Como en 'put'. No tiene un equivalente en español.",
    "u": "Como en 'tú'. Es una vocal cerrada posterior redondeada.",
    "ɑ": "Como en 'father'. No tiene un equivalente en español."
}

# Errors typical of Spanish-speaking learners of English. Keys: "{target}_{produced}".
# Hints are written in Spanish.
ERROR_MAP_ES: dict[str, str] = {
    "p": "Como en 'papa'. Es un sonido bilabial sordo.",
    "b": "Como en 'banco'. Es un sonido bilabial sonoro.",
    "t": "Como en 'taco'. Es un sonido alveolar sordo.",
    "d": "Como en 'deber'. Es un sonido alveolar sonoro.",
    "k": "Como en 'casa'. Es un sonido velar sordo.",
    "g": "Como en 'gato'. Es un sonido velar sonoro.",
    "m": "Como en 'mamá'. Es un sonido bilabial nasal.",
    "n": "Como en 'nube'. Es un sonido alveolar nasal.",
    "ŋ": "Como en 'sing' (no tiene equivalente en español). Es un sonido nasal velar.",
    "f": "Como en 'flor'. Es un sonido labiodental sordo.",
    "v": "Como en 'vaca'. Puede ser un sonido labiodental sonoro, similar al 'b' en algunas regiones.",
    "θ": "Como en 'cima' (en España). Es un sonido dental sordo, no lo hay en español latino.",
    "ð": "Como en 'this'. No tiene equivalente en español.",
    "s": "Como en 'sopa'. Es un sonido alveolar sordo.",
    "z": "Como en 'casa' (en algunas regiones de España). Es un sonido alveolar sonoro.",
    "ʃ": "Como en 'shampoo'. No tiene equivalente en español.",
    "ʒ": "Como en 'measure'. No tiene equivalente en español.",
    "h": "Como en 'hola' (en inglés suele ser un sonido glotal sordo).",
    "l": "Como en 'luz'. Es un sonido alveolar lateral.",
    "r": "Como en 'ratón'. Es un sonido alveolar que puede ser vibrante.",
    "j": "Como en 'yo'. Es un sonido palatal aproximante.",
    "w": "Como en 'huevo'. Es un sonido labio-velar aproximante.",
    "i": "Como en 'sí'. Es una vocal cerrada anterior no redondeada.",
    "ɪ": "Como en 'bit'. No tiene equivalente exacto en español.",
    "e": "Como en 'rey'. Es una vocal media anterior no redondeada, similar a la diptongación en español.",
    "æ": "Como en 'cat'. No tiene equivalente directo en español.",
    "ʌ": "Como en 'cup'. No hay un equivalente exacto en español.",
    "ɔ": "Como en 'thought'. No tiene equivalente directo en español.",
    "o": "Como en 'fotografía'. Es una vocal cerrada posterior redondeada.",
    "ʊ": "Como en 'put'. No tiene un equivalente en español.",
    "u": "Como en 'tú'. Es una vocal cerrada posterior redondeada.",
    "ɑ": "Como en 'father'. No tiene un equivalente en español."
}
